### PR TITLE
All the required variables defined + l2 with json output completed

### PR DESCRIPTION
**Pull request by gaurav-calsoft**

### CODE REVIEW

**Comment by ashxjain** [comment]
Can you also paste the output here.

I see that you have modified the standard json callback, rather than doing that write a custom callback (which can be same as json one with your modifications) and see how to call it.

**Comment by ramanujjaju** [comment]
Nice work Gaurav. I agree with Ashish. We can customize it as `pn_json.py` or something and specify the path in the `ansible.cfg` file:
```
# set plugin path directories here, separate with colons
#action_plugins     = /usr/share/ansible/plugins/action
#callback_plugins   = /usr/share/ansible/plugins/callback
#connection_plugins = /usr/share/ansible/plugins/connection
#lookup_plugins     = /usr/share/ansible/plugins/lookup
#vars_plugins       = /usr/share/ansible/plugins/vars
#filter_plugins     = /usr/share/ansible/plugins/filter
#test_plugins       = /usr/share/ansible/plugins/test
#strategy_plugins   = /usr/share/ansible/plugins/strategy
```
And may be change here also?
```
# change the default callback
#stdout_callback = skippy
# enable additional callbacks
#callback_whitelist = timer, mail
```

**Comment by gaurav-calsoft** [comment]
@ashxjain @ramanujjaju Created a separate plugin file named json_modified. We can use that

**Comment by amitsi** [comment]
Please get documented ramanuj

**Comment by ramanujjaju** [comment]
Sure

**Pull request merged**
