### PR TITLE
Removed unnecessary modules and kept only those required for GUI

### PR DESCRIPTION
**Pull request by saptaktakalkar**
Only kept modules that are required for fabric creation, L2 vrrp and switch config reset (those playbooks which are currently present in playbooks folder)

### CODE REVIEW

**Comment by ashxjain** [comment]
I dont see l2 vrrp here, also fabric playbook.

**Comment by saptaktakalkar** [comment]
Because they are already present in library. I have just removed other unused/unnecessary modules. :)

**Comment by ashxjain** [comment]
Oh Okay Sorry. Can you put the list of files here which are there now?

**Comment by saptaktakalkar** [comment]
Here is the list of modules which are currently present in library:
- `pn_initial_ztp.py`
- `pn_l2_ztp.py`
- `pn_ztp_vrrp_l2_csv.py`
- `pn_switch_config_reset.py`

**Comment by ashxjain** [comment]
Ok. We don't do l2 ZTP. Currently it is only fabric creation and l2 vrrp. (And switch config reset)

**Comment by saptaktakalkar** [comment]
L2 ztp module is required for L2 vrrp. We first configure vlags and then configure vrrp for L2.

**Pull request merged**
