### PR TITLE
code modified

### PR DESCRIPTION
**Pull request by galactro55**

### CODE REVIEW

**Comment by amitsi** [comment]
Missing sys-flow-setting-modify no-auto-trunk module for l3

**Comment by amitsi** [comment]
Also please run pylint on this module.....there is a bunch of issues to fix and pylint will show you

**Comment by galactro55** [comment]
Hi,

This is not missing. Its under the function disable_trunk inside L3.

**Comment by galactro55** [comment]
This was commented because we were getting errors for many commands 
initially and our code was working fine without switch-local.

**Pull request closed without merging**
