### PR TITLE
[release-2.3.0] Removed pn_assign_loopback variable

### PR DESCRIPTION
**Pull request by saptaktakalkar**

### CODE REVIEW

**Comment by amitsi** [comment]
remove what? why?

**Comment by saptaktakalkar** [comment]
@amitsi `pn_assign_loopback` is boolean variable to decide if loopback ips should be assigned to vrouters or not during L3 ztp config. During OSPF config, when we add ospf neighbors to spines, we use loopback ips. So if we do not assign loopback ips during L3 config, ospf neighbor assignment fails. So that's why we have decided to remove this boolean variable and always assign loopback ips.

**Comment by ashxjain** [comment]
@saptaktakalkar Let's not remove this variable. If it is false, no loopback should be configured.

In case of OSFP, we'll have not put those arguments.

**Comment by saptaktakalkar** [comment]
@ashxjain If no loopback ips have been configured then how should we assign ospf neighbors for spines?

**Comment by ashxjain** [comment]
@saptaktakalkar I think so we can skip, adding ospf neighbor for loopback spines. But i'll wait for @amitsi to comment on this

**Comment by saptaktakalkar** [comment]
@ashxjain aaa tacacs changes has been pushed. Last commit in this PR.

**Pull request merged**
