### PR TITLE
added assigning static mgmt-ip code

### PR DESCRIPTION
**Pull request by gaurav-calsoft**

### CODE REVIEW

**Comment by saptaktakalkar** [comment]
This code is redundant and not needed since we already have a method in this `pn_initial_ztp` module to add static values to switch-setup.
https://github.com/amitsi/pluribus-ansible/blob/master/ansible/library/pn_initial_ztp.py#L262-L279

**Comment by amitsi** [comment]
@saptaktakalkar it doesnt work, is it on by default

**Comment by saptaktakalkar** [comment]
@amitsi Default is False. https://github.com/amitsi/pluribus-ansible/blob/master/ansible/library/pn_initial_ztp.py#L548
Need to update playbook documentation

**Comment by saptaktakalkar** [comment]
@amitsi You need to set `pn_static_setup` flag to `True` in the playbook and uncomment all setup attributes from the playbook for which you want to set a static values.

**Pull request closed without merging**
