### PR TITLE
Created separate playbook for l2 vrrp csv validation

### PR DESCRIPTION
**Pull request by saptaktakalkar**
Output:

```
root@amitsi:/etc/ansible/pluribus-ansible/ansible/playbooks# ansible-playbook -i hosts l2_csv_validation.yml 
__________ANSIBLE_TASK_BOUNDARY_STARTS__________
{
    "plays": [
        {
            "play": {
                "id": "201a6e18-a5b1-4f7c-9f50-d0dc3f27f1d5", 
                "name": "Validate L2 VRRP CSV File"
            }, 
            "tasks": [
                {
                    "hosts": {
                        "localhost": {
                            "_ansible_no_log": false, 
                            "_ansible_parsed": true, 
                            "changed": false, 
                            "exception": "", 
                            "failed": true, 
                            "invocation": {
                                "module_args": {
                                    "pn_csv_data": "1a1.108.100.0/24, 100, test-spine1\n101.108.101.0/24, 10199, test-spine1\n101.108.102.0/24, 102, test-spine2\n101.108.103.0/24, 103, test-spine2\n198.168.1.1/32, 102, test-spine2\n , , , , , \n, ,"
                                }, 
                                "module_name": "pn_l2_vrrp_csv_validation"
                            }, 
                            "msg": "Invalid csv file", 
                            "summary": "Invalid IP 1a1.108.100.0/24 at line number 1\nInvalid VLAN ID 10199 at line number 2\nDuplicate vlan entry at line number 5. A router can have only one interface per vlan\nInvalid number of elements at line number 6. It should have 3 elements (IP, Vlan, Switch)\nInvalid entry at line number 7\n", 
                            "task": "Validate L2 VRRP csv file", 
                            "unreachable": false
                        }
                    }, 
                    "status": "1", 
                    "task": {
                        "id": "bae34b66-a5e4-4353-9be6-f4cf9b0f90d1", 
                        "name": "Validate L2 VRRP csv file"
                    }
                }
            ]
        }
    ]
}
__________ANSIBLE_TASK_BOUNDARY_ENDS__________
	to retry, use: --limit @/etc/ansible/pluribus-ansible/ansible/playbooks/l2_csv_validation.retry
{
    "stats": {
        "localhost": {
            "changed": 0, 
            "failures": 1, 
            "ok": 0, 
            "skipped": 0, 
            "unreachable": 0
        }
    }
}

```

### CODE REVIEW

**Comment by saptaktakalkar** [comment]
@ashxjain If `"msg": "Invalid csv file"` then front-end will have to look at `summary` field and parse the output on `\n`.
If `"msg": "Valid csv file"` then they can go ahead for l2 vrrp playbook execution.

**Comment by ashxjain** [comment]
No, If status is 1 then they only look at "msg" and not summary.

If status is 0, then they look at "summary". Hence have this logic:

1. If status is 0, then continue with L2 VRRP playbook selection
2. If status is 1, then look at msg and display error ["msg"] on GUI

**Comment by saptaktakalkar** [comment]
@ashxjain Yes, this is how it is working right now. Here is the output for Valid csv file (status is 0 in this case):

```
__________ANSIBLE_TASK_BOUNDARY_STARTS__________
{
    "plays": [
        {
            "play": {
                "id": "8ddef5a9-92d9-43a0-9a17-81274b5f8c09", 
                "name": "Validate L2 VRRP CSV File"
            }, 
            "tasks": [
                {
                    "hosts": {
                        "localhost": {
                            "_ansible_no_log": false, 
                            "_ansible_parsed": true, 
                            "changed": false, 
                            "exception": "", 
                            "failed": false, 
                            "invocation": {
                                "module_args": {
                                    "pn_csv_data": "101.108.102.0/24, 102, test-spine2\n101.108.103.0/24, 103, test-spine2\n198.168.1.1/32, 104, test-spine2"
                                }, 
                                "module_name": "pn_l2_vrrp_csv_validation"
                            }, 
                            "msg": "Valid csv file", 
                            "summary": "", 
                            "task": "Validate L2 VRRP csv file", 
                            "unreachable": false
                        }
                    }, 
                    "status": "0", 
                    "task": {
                        "id": "1a7def81-6226-4d18-a261-e1cecafd54c4", 
                        "name": "Validate L2 VRRP csv file"
                    }
                }
            ]
        }
    ]
}
__________ANSIBLE_TASK_BOUNDARY_ENDS__________
{
    "stats": {
        "localhost": {
            "changed": 0, 
            "failures": 0, 
            "ok": 1, 
            "skipped": 1, 
            "unreachable": 0
        }
    }
}

```

**Comment by saptaktakalkar** [comment]
For invalid csv file, status is 1. 
See the invalid output in PR description

**Comment by saptaktakalkar** [comment]
@ashxjain I have only one concern. If GUI is only going to display `msg` then it won't be very informative. Since right now, `msg` only holds whether csv file is valid or invalid. In case of invalid, details of invalid entries are stored in `summary` field. Do we want to keep it this way only or do we want to update the `msg` field to contain details of invalid fields just like `summary`?

**Comment by ashxjain** [comment]
Right. For status 1, should have "summary" output in "msg"? Because "status=1" is already an indicator of invalid csv file, so "msg" is not giving any extra information.

**Comment by ashxjain** [comment]
Yes. Let's have "summary" in "msg".

**Comment by saptaktakalkar** [comment]
Ok cool. I will push the update.

**Comment by saptaktakalkar** [comment]
@ashxjain Done here: https://github.com/amitsi/pluribus-ansible/pull/166/commits/43a61e819c257f5201eb6ee6f67f6af03ef039e3

**Comment by saptaktakalkar** [comment]
Please let Amar and Ajinkya know about this new playbook along with output when you merge it.

**Pull request merged**
